// Original FileFlow guide copy; source links explain the method and its licence.
export const johnnyDecimal = {
  en: {
    title: 'Johnny.Decimal on Mac',
    description: 'Understand the folder structure, then put it to work with FileFlow. A practical guide with a real Mac workflow.',
    lead: 'Give your files a place. Keep the next decision clear.',
    label: 'A FILEFLOW GUIDE',
    sections: [
      ['A place you can name.', 'Johnny.Decimal is a way to organize information into numbered areas, categories, and IDs, with an index to help you find it again. An area groups related categories; a category contains IDs for particular subjects. In a filesystem, an ID can name a folder containing several related files. You do not need a new number for every PDF.'],
      ['Start with a structure. Make it useful.', 'FileFlow can initialize a built-in starting structure based on Johnny.Decimal. This is FileFlow\'s template, not an official Johnny.Decimal product. The small sample library shown here illustrates the method; it is not the complete built-in template. Choose names and groupings that reflect the work you actually do.'],
      ['Then, handle the files that arrive.', 'A directory gives a file a possible home. You still need to decide whether it belongs there. FileFlow brings that decision and the proposed file operation into a Mac workspace, with a plan to review before execution.'],
      ['Keep what already works.', 'Numbered locations are useful when you repeatedly return to the same subjects and want a consistent way to refer to them. They take some thought to set up and maintain. If your current folders already make sense, FileFlow can use an existing structure instead. You do not need to reorganize an entire disk, adopt every part of the method, or configure AI to try the manual workflow.'],
      ['Learn the method. Try the workflow.', 'The official documentation explains the wider Johnny.Decimal system, including its index and practices beyond folders. This page is a FileFlow walkthrough, not a replacement for that documentation. For your first run, our step-by-step guide starts with three disposable file copies.'],
    ],
    example: '20-29 Work/\n  21 Projects/\n    21.01 Project Documents/\n      Project kickoff.txt\n      Meeting notes.txt\n      Delivery checklist.txt',
    exampleLabel: 'One part of a FileFlow sample library',
    parts: [
      ['20-29', 'Area', 'Work is the broad grouping.'],
      ['21', 'Category', 'Projects sits within Work.'],
      ['21.01', 'ID', 'Project Documents is one location for related files.'],
    ],
    exampleNote: 'The names give the numbers meaning. In this example, 21.01 identifies the folder, not a date, a priority, or a single document.',
    officialIntro: 'Read the official introduction',
    indexNote: 'FileFlow keeps an operational index for its library. This does not imply synchronization with an external Johnny.Decimal index or note-taking app.',
    steps: [
      ['Choose a small starting point.', 'Use separate test source and archive folders with disposable file copies. During setup, choose the template or an existing structure, check the selected path, and authorize the folders. Initialization may create folders and FileFlow metadata; it is separate from organizing source files.'],
      ['Choose where a file belongs.', 'Scan the source folder in Inbox. Select a sample file, choose Archive to..., pick its destination, and confirm. The manual path does not require an AI provider.'],
      ['Read the plan before you execute.', 'In Review Plan, check the full source and destination paths and the name-conflict policy. Back returns without running the plan. Choose Execute only when the plan is right. Avoid overwriting files in your first trial.'],
      ['Check the result.', 'Read the operation results and open the actual destination files. An activity record alone is not proof that every file is intact. Keep independent backups: Undo cannot restore the old contents of an overwritten file.'],
    ],
    browseCaption: 'Browse keeps the numbered location and its files together. Real FileFlow capture with sample data.',
    planCaption: 'Review Plan shows source paths, destinations, and conflict handling before execution. Real FileFlow capture with sample data.',
    resources: ['Johnny.Decimal documentation', 'Johnny.Decimal licence and name usage'],
    attribution: 'Johnny.Decimal is a trademark of Coruscade Pty Ltd, Australia. FileFlow is an independent product and is not affiliated with or endorsed by Johnny.Decimal. The examples on this page are FileFlow examples, not official Johnny.Decimal templates or redistributed paid content.',
  },
  zh: {
    title: '在 Mac 上实践 Johnny.Decimal',
    heading: '在 Mac 上实践\nJohnny.Decimal',
    description: '先理解编号目录，再用 FileFlow 处理实际文件。从一个具体示例开始，走进真实的 Mac 整理流程。',
    lead: '给文件一个位置，让下一步决定更清楚。',
    label: 'FILEFLOW 实践指南',
    sections: [
      ['一个说得清的位置。', 'Johnny.Decimal 用带编号的区域、类别和 ID 组织信息，再通过索引帮助你找到它们。区域包含相关类别，类别下的 ID 对应具体主题。用在文件系统中，一个 ID 可以是存放多份相关文件的目录，不必给每一份 PDF 都编一个新号码。'],
      ['从结构开始，让它适应工作。', 'FileFlow 可以初始化一套基于 Johnny.Decimal 的内置起始结构。这是 FileFlow 提供的模板，并非 Johnny.Decimal 官方产品。本页的小型示例资料库用于说明方法，不是完整的内置模板。目录名称与分组，应当贴近你实际处理的事情。'],
      ['然后，处理不断进来的文件。', '目录为文件提供一个可能的归属，你仍然需要判断它是否属于那里。FileFlow 把这个决定与即将发生的文件操作放在同一个 Mac 工作区，让你在执行前先看清计划。'],
      ['保留已经顺手的部分。', '如果你经常回到相同主题，并希望用稳定的位置指代资料，编号目录会很有用；但建立和维护它也需要思考。如果已有目录已经清楚，FileFlow 也可以沿用现有结构。不必重整整个磁盘、采用方法的所有部分，或配置 AI，才能尝试手动整理。'],
      ['深入理解，动手试一次。', '官方文档介绍了更完整的 Johnny.Decimal 系统，包括索引以及文件夹之外的实践。本页介绍 FileFlow 的使用场景，不替代官方文档。第一次试用，可以跟随我们的分步指南，从三份可丢弃的文件副本开始。'],
    ],
    example: '20-29 工作/\n  21 项目/\n    21.01 项目文档/\n      项目启动.txt\n      会议记录.txt\n      交付清单.txt',
    exampleLabel: 'FileFlow 示例资料库的一部分',
    parts: [
      ['20-29', '区域', '“工作”是较大的分组。'],
      ['21', '类别', '“项目”属于工作区域。'],
      ['21.01', 'ID', '“项目文档”为相关文件提供共同位置。'],
    ],
    exampleNote: '名称赋予编号含义。在这个例子中，21.01 标识一个目录，不是日期、优先级或某一份文档。',
    officialIntro: '阅读官方入门文档（英文）',
    indexNote: 'FileFlow 会维护资料库的操作索引，但这不代表它会与外部 Johnny.Decimal 索引或笔记应用同步。',
    steps: [
      ['选一个小范围开始。', '准备互不包含的试用来源与归档目录，使用可丢弃的文件副本。在设置中选择模板或现有结构，核对路径并授权目录。初始化可能创建文件夹与 FileFlow 管理数据，这与整理来源文件是两件事。'],
      ['选择文件的归属。', '在 Inbox 扫描来源目录，选中示例文件，点击 Archive to...，选择目标位置并确认。这条手动路径不需要 AI 服务商。'],
      ['执行前，先阅读计划。', '在 Review Plan 中核对完整来源与目标路径，以及重名处理方式。选择 Back 返回不会执行计划；确认正确后，再选择 Execute。第一次试用请避免覆盖已有文件。'],
      ['核对实际结果。', '阅读操作结果，打开目标位置的实际文件。单独一条活动记录不能证明所有文件都完整可用。请保留独立备份：撤销不能恢复被覆盖文件的旧内容。'],
    ],
    browseCaption: '目录浏览把编号位置与其中的文件放在一起。FileFlow 真实截图，使用示例数据，界面为英文。',
    planCaption: '执行前，整理计划展示来源路径、目标位置与重名处理方式。FileFlow 真实截图，使用示例数据，界面为英文。',
    resources: ['Johnny.Decimal 官方文档（英文）', 'Johnny.Decimal 许可与名称使用说明（英文）'],
    attribution: 'Johnny.Decimal 是澳大利亚 Coruscade Pty Ltd 的商标。FileFlow 是独立产品，与 Johnny.Decimal 无隶属关系，也未获其背书。本页示例来自 FileFlow，并非 Johnny.Decimal 官方模板或其付费内容的再分发。',
  },
};
