// Shared product facts and bilingual copy. Generated HTML also works without JavaScript.
export const site = {
  origin: 'https://fileflow.theunclej.com',
  store: 'https://apps.apple.com/app/fileflow-file-organizer/id6756985211?mt=12',
  email: 'fileflow@theunclej.com',
};

export const copy = {
  en: {
    lang: 'en', language: 'English', other: '简体中文', skip: 'Skip to content',
    nav: ['Workflow', 'Guide', 'Support'], footer: ['Product', 'Principles', 'Support', 'Privacy', 'Terms', 'Guide'],
    guideLink: 'Your first three files', guideIntro: 'A small first step. A workflow you can trust.',
    title: 'FileFlow | A considered way to organize files on Mac',
    description: 'Review files, choose destinations, and preview a plan before organizing. A native Mac workspace with optional AI assistance.',
    eyebrow: 'A native workspace for your files',
    lead: 'Organize files.\nKeep what works.',
    intro: 'Review your files. Choose where they belong.\nOrganize when you are ready.',
    download: 'View on the Mac App Store', requirement: 'macOS 14 or later · No FileFlow account required',
    screenshotNote: 'FileFlow 1.1 · Real app captures with sample files',
    workflowLabel: 'THE WORKFLOW', workflowTitle: 'See the change before you make it.',
    workflowIntro: 'From a loose file to a considered destination. Each workspace keeps the next decision in view.',
    screens: [
      { key: 'plan', file: '02-plan-commit.png', label: 'Plan', title: 'Know what will move where.', text: 'Inspect source paths, destinations, and name conflicts in one plan. Nothing in that plan runs until you choose Execute.', alt: 'FileFlow Review Plan showing source and destination paths and a Keep Both conflict policy' },
      { key: 'browse', file: '03-browse-structure.png', label: 'Browse', title: 'Keep the structure that makes sense to you.', text: 'Start with a Johnny.Decimal template or use your existing folders. Browse your library without giving up its context.', alt: 'FileFlow Browse workspace with an expanded folder tree and project documents' },
      { key: 'activity', file: '04-statistics.png', label: 'Activity', title: 'A clearer picture of your progress.', text: 'See recorded organizing activity and the distribution of indexed files. Check what happened, then return to your work.', alt: 'FileFlow Statistics showing recorded file activity and indexed file distribution' },
      { key: 'ai', file: '05-ai-optional.png', label: 'Optional AI', title: 'Suggestions, on your terms.', text: 'Connect your own API provider or a separately running Ollama service. Review its suggestions. The destination is still your decision.', alt: 'FileFlow AI settings with optional API and local LLM connection modes' },
    ],
    reviewAlt: 'FileFlow 1.1 Review workspace with sample files, document preview, and destination selection',
    expand: 'Enlarge screenshot', close: 'Close screenshot',
    principlesLabel: 'A LITTLE MORE DELIBERATE', principlesTitle: 'Your folders. Your decisions.',
    principles: [
      ['01', 'Start with what you have.', 'Keep an existing folder structure or build a new one from a Johnny.Decimal template. There is no requirement to start over.'],
      ['02', 'Keep AI optional.', 'The manual workflow needs no AI account, key, or model. Add classification suggestions only when they are useful to you.'],
      ['03', 'Leave room to review.', 'Inspect the proposed changes before execution, then check the results. Recovery information is useful, but it is never a substitute for a backup.'],
    ],
    principlesLink: 'Read the principles',
    limitsLabel: 'CLEAR BOUNDARIES', limitsTitle: 'Confidence starts with knowing the limits.',
    limits: [
      ['AI connections', 'Cloud classification sends metadata, including filenames, and candidate destinations to your chosen provider. Its fees and data policies may apply.'],
      ['Undo and recovery', 'Undo is available for eligible recent runs, subject to permissions and file availability. It cannot restore the previous contents of overwritten files.'],
    ],
    privacyLink: 'How data is handled', supportLink: 'Help with your workflow',
    pricingLabel: 'GET FILEFLOW', pricingTitle: 'Start with a few files.',
    pricingText: 'The free tier includes 50 file operations in total, not a monthly allowance. An optional Pro purchase removes that quota. Check the App Store and in-app purchase sheet for current local pricing.',
    pricingAI: 'Third-party AI services are separate and may charge for usage.',
    faqTitle: 'A few things worth knowing.',
    faqs: [
      ['Do I need AI?', 'No. Choose destinations manually and review the plan without configuring an AI provider. Cloud AI requires a network connection; local Ollama requires a running service and model.'],
      ['Will FileFlow replace my folder structure?', 'You can use an existing folder structure or initialize a Johnny.Decimal template. You choose the archive root and source folders during setup.'],
      ['Can I undo everything?', 'No. Recovery depends on the operation, file availability, permissions, and retained recovery data. Some recoveries may retain archive copies or need manual action. Overwritten old contents are not recoverable through Undo. Keep independent backups.'],
      ['Where can I get help?', 'Visit Support for the manual workflow, connection checks, and recovery guidance. You can also contact fileflow@theunclej.com.'],
    ],
    docs: {
      guide: { title: 'Your first three files.', description: 'A small trial. From your first folder to your first plan.', sections: [
        ['1. Make a little room to experiment', 'Create two separate local folders: FileFlow Test Source and FileFlow Test Archive. Neither should be inside the other. Put three disposable, non-sensitive copies in the source folder, such as a TXT, PNG, and PDF. Keep the originals elsewhere. For this first trial, avoid synced cloud folders and external drives.'],
        ['2. Choose your folders', 'During setup, select and authorize the test archive folder. Choose a Johnny.Decimal template, or use an existing structure with a destination subfolder you have created. Add the test source folder. Check the full path before approving initialization: setup may create FileFlow metadata, which is separate from organizing your source files. Skip AI for this first run.'],
        ['3. Choose a destination', 'Open Inbox and scan the source folder. Select your three sample files, choose Archive to..., then select a destination and confirm the selection. This opens Review Plan; it does not execute the plan.'],
        ['4. Read the plan', 'Check the selected files, full source and destination paths, and the name-conflict policy. For this trial, do not overwrite an existing file. Choose Back to revise the selection, or Execute when the plan is correct. Undo cannot recover the previous contents of a file that has been overwritten.'],
        ['5. Check the actual result', 'Read the operation results, then open the destination folder and check that the files can be opened. A partially failed run is not a successful batch. Browse and Statistics provide useful views, but an index or recorded receipt alone does not prove that every file is intact.'],
        ['6. Try an eligible Undo', 'Use the available Undo action for the recent run and read its prompts. For a normal archive operation, recovery may restore the source while keeping an archive copy. It may also use a Recovered location or require manual action. Check both locations afterward. If Undo is unavailable, retain the files and metadata and read the reason.'],
        ['7. Add AI later, if it helps', 'Configure the endpoint, model, protocol, and your authorized key in Settings, then verify and save the connection. A successful connection test does not prove that classifications are correct. Request classification, review each suggested destination, then use Preview Selection to inspect the plan. Cloud requests send metadata and candidate destinations to your provider. Use non-sensitive sample files.'],
        ['If something interrupts the flow', 'Check source and destination files before retrying. A destination may contain a partial copy. Abort or Dismiss is not Undo and does not automatically remove fragments or restore files. Do not repeatedly execute a blocked plan or delete metadata to bypass a warning. Preserve the original files and the reported recovery information.'],
        ['When a root or its metadata is missing', 'First confirm the original folder or disk is available and reauthorize access if needed. Do not treat an inaccessible folder as an empty one to initialize again. Recovery receipts may help explain recent operations, but cannot reconstruct missing contents. Use the original location or an independent backup.'],
        ['Then, a few more files', 'Once you have inspected a plan, checked the result, and understood the recovery behavior, expand gradually. You do not need to start by organizing an entire disk.'],
      ] },
      support: { title: 'Support', description: 'Start small. Keep the plan in view.', sections: [
        ['Start with a test folder', 'Use disposable sample files for your first run. Select a dedicated archive folder, then choose an existing structure with a destination folder or initialize a Johnny.Decimal template. Add a separate source folder. You can skip AI setup.'],
        ['The manual workflow in 1.1', 'Open Inbox and scan. Select files, choose Archive to..., and select a destination. Inspect Review Plan, including source paths and conflict handling. Choose Execute to organize, or Back to leave without running the plan. Then inspect the results.'],
        ['Working with suggestions', 'For items already in Review, change the destination as needed, then use Preview Selection to inspect the plan. Scanning alone does not guarantee that classified items appear in Review.'],
        ['Connect an AI provider', 'In Settings, configure the provider endpoint, model, and matching protocol: OpenAI-compatible or Anthropic Messages. Supply your own authorized API key, verify the connection, then save. Ollama needs a separately running service and model. A connection test sends a synthetic filename; actual classification sends file metadata and candidate destinations.'],
        ['Folder access and missing files', 'Check that the source and archive folders are accessible. Reauthorize a folder in Settings if macOS access has expired. For iCloud Drive locations, check that the files are downloaded. Avoid moving or renaming active source and archive folders during a run.'],
        ['Interrupted operations and Undo', 'Read the reported results and recovery information before retrying. Do not delete recovery metadata to dismiss a warning. Eligible Undo may restore a file, retain an archive copy, use a Recovered location, or require manual action. It cannot reconstruct deleted contents or recover old overwritten contents.'],
        ['Restore a purchase', 'Use the purchase restoration control in Settings while signed in to the Apple Account used for the purchase. Restore requires communication with the App Store. If the entitlement is not restored, note the displayed result and contact support.'],
        ['Contact', 'Email fileflow@theunclej.com with your app version, macOS version, steps to reproduce, and the displayed error. Redact private paths and filenames from screenshots. Never send API keys or sensitive documents.'],
      ] },
      philosophy: { title: 'Principles', description: 'Organizing should preserve context, not erase it.', sections: [
        ['Not every folder needs a fresh start', 'An inbox and a project archive serve different purposes. A pile of downloads may need sorting; an established project may already have meaningful internal order. Your existing structure deserves a place in the workflow.'],
        ['Decisions before automation', 'A suggestion is not permission. FileFlow separates choosing destinations from executing the resulting plan, so you can inspect the proposed change before it happens.'],
        ['AI is an assistant, not a prerequisite', 'Manual organization is a complete path through the product. An external model can suggest classifications, but using it should remain a deliberate choice.'],
        ['Records are useful. Backups are different.', 'Activity and recovery records help explain an operation. They are not copies of every past file state. Honest limits matter more than promising that everything can be undone.'],
        ['Order that fits your work', 'Use a Johnny.Decimal template or your own folders. The point is not a perfect taxonomy. It is a structure you can keep using and understand when you return.'],
      ] },
      privacy: { title: 'Privacy', description: 'Local organization. Explicit external connections.', updated: 'Updated September 12, 2026', sections: [
        ['Scope', 'This page describes FileFlow 1.1 and this product website. FileFlow does not require a FileFlow account for core manual organization. Optional AI connections, App Store services, cloud-backed folders, and support correspondence have distinct data flows.'],
        ['Files and local storage', 'Core file organization runs on your Mac using the folders you authorize. The archive root may contain .fileflow indexes, configuration, operation history, journals, and recovery metadata. The app also stores configuration, folder access bookmarks, and recovery summaries in its application-support storage. API credentials are stored in macOS Keychain. These records can contain filenames and paths.'],
        ['Optional AI requests', 'When you request cloud classification, FileFlow sends file metadata and candidate destinations to your configured endpoint. This can include filenames, extensions, source-folder names, file sizes, and folder structure. The classification prompts use metadata rather than file contents. Names and paths can still reveal sensitive information. Connection verification sends a synthetic filename to the endpoint.'],
        ['Your provider', 'Your configured AI provider receives the requests and handles them under its own data policies. Its retention practices, availability, and fees are outside FileFlow’s control. An Ollama connection requires a separate service and model; whether that endpoint is local depends on your configuration.'],
        ['Apple and cloud-backed folders', 'App Store purchases and restoration are handled through Apple. If you organize files in iCloud Drive or another synced location, that service may synchronize the changes under its own policies. FileFlow does not turn a synced folder into an offline-only location.'],
        ['Diagnostics and support', 'FileFlow keeps operational diagnostics locally; the 1.1 build does not enable its optional third-party crash-reporting integration. If you email support, your email address and the information you choose to send are used to respond to your request. Do not send API keys or sensitive file contents.'],
        ['This website', 'This website does not include advertising trackers or analytics scripts. Hosting providers may process ordinary connection information to deliver the site. Following the App Store link takes you to Apple’s service.'],
        ['Your choices', 'You can use the manual workflow without AI and remove saved AI credentials through the app. Local configuration and recovery records may persist independently of app removal. Before deleting metadata or revoking folder access, finish any pending recovery and keep backups of your files. For privacy questions, contact fileflow@theunclej.com.'],
      ] },
      terms: { title: 'Terms', description: 'Clear responsibilities for working with your files.', updated: 'Updated September 12, 2026', sections: [
        ['Using FileFlow', 'By using FileFlow, you agree to these terms. FileFlow is a file organization tool for Mac, with manual workflows and optional AI classification. You review destinations and approve organization plans before execution.'],
        ['Your responsibilities', 'You are responsible for maintaining independent backups, authorizing appropriate folders, and reviewing proposed file operations. Undo is limited by file availability, permissions, and recovery data. It cannot restore the previous contents of overwritten files. FileFlow is not a backup service.'],
        ['Optional AI services', 'You manage your own provider credentials and any costs charged by your provider. Cloud AI receives metadata and candidate destinations under that provider’s policies. Ollama requires a separate service and model. Provider compatibility and availability depend on the selected endpoint, model, and protocol.'],
        ['Purchases', 'FileFlow offers a limited free tier and an optional Pro purchase. The App Store and in-app purchase sheet show applicable pricing and purchase terms. Third-party AI charges are separate. Refund requests are handled by Apple under its App Store policies.'],
        ['Disclaimer', 'FileFlow is provided “as is” without warranties of any kind. Although the app includes plan review, verification, operation records, and recovery mechanisms, these do not guarantee against data loss. We cannot be held liable for data loss to the extent permitted by applicable law.'],
        ['Changes and contact', 'We may update these terms. Continued use of FileFlow after changes means you accept the updated terms. Questions can be sent to fileflow@theunclej.com.'],
      ] },
    },
  },
  zh: {
    lang: 'zh-Hans', language: '简体中文', other: 'English', skip: '跳至正文',
    nav: ['整理流程', '使用指南', '支持'], footer: ['产品', '产品理念', '支持', '隐私', '条款', '使用指南'],
    guideLink: '从三个文件开始', guideIntro: '先试一小步，再放心继续。',
    title: 'FileFlow | Mac 文件整理，先审核再执行',
    description: '先审核文件，选择目标位置，再预览整理计划。原生 Mac 工作区，支持已有目录结构与可选 AI 分类建议。',
    eyebrow: '为 Mac 文件整理而设计',
    lead: '整理文件。\n保留你熟悉的秩序。',
    intro: '审核文件，选择归属位置。\n准备好后，再执行整理。',
    download: '前往 Mac App Store', requirement: 'macOS 14 或更新版本 · 无需 FileFlow 账号',
    screenshotNote: 'FileFlow 1.1 · 使用示例文件的真实应用截图',
    workflowLabel: '整理流程', workflowTitle: '先看清变更，再执行整理。',
    workflowIntro: '从待整理的文件，到有意义的归属位置。每个工作区，都让下一步决定更清楚。',
    screens: [
      { key: 'plan', file: '02-plan-commit.png', label: '整理计划', title: '文件将移到哪里，一目了然。', text: '在同一份计划中核对来源、目标路径与重名处理方式。选择执行之前，计划中的操作不会开始。', alt: 'FileFlow 整理计划：展示来源路径、目标路径以及保留两个文件的重名策略，界面为英文' },
      { key: 'browse', file: '03-browse-structure.png', label: '目录浏览', title: '沿用你熟悉的目录结构。', text: '从 Johnny.Decimal 模板开始，或使用已有的文件夹。在清晰的层级中浏览文件，保留工作的上下文。', alt: 'FileFlow 目录浏览：展开的文件夹树与项目文档，界面为英文' },
      { key: 'activity', file: '04-statistics.png', label: '整理记录', title: '整理进展，有迹可循。', text: '查看已记录的整理活动和已索引文件的分布。核对发生了什么，再继续手头的工作。', alt: 'FileFlow 统计：已记录的整理活动和已索引文件分布，界面为英文' },
      { key: 'ai', file: '05-ai-optional.png', label: '可选 AI', title: 'AI 提建议，你做决定。', text: '连接自己的 API 服务商，或另行运行的 Ollama 服务。审核分类建议，文件的最终归属仍由你决定。', alt: 'FileFlow AI 设置：API 与本地模型连接选项，界面为英文' },
    ],
    reviewAlt: 'FileFlow 1.1 审核工作区：示例文件、文档预览和目标位置选择，界面为英文',
    expand: '放大截图', close: '关闭截图',
    principlesLabel: '多一点审慎', principlesTitle: '你的目录，你来决定。',
    principles: [
      ['01', '从已有的文件开始。', '保留现有目录结构，或从 Johnny.Decimal 模板建立新结构。不必为了整理，先把一切推倒重来。'],
      ['02', 'AI 始终是可选项。', '手动整理不需要 AI 账号、密钥或模型。只有在需要分类建议时，再连接 AI。'],
      ['03', '为审核留出一步。', '执行前检查计划，执行后核对结果。恢复记录很有用，但不能代替独立备份。'],
    ],
    principlesLink: '了解产品理念',
    limitsLabel: '明确边界', limitsTitle: '清楚能力，也清楚限制。',
    limits: [
      ['AI 连接', '云端分类会将文件名等元数据及候选目标位置发送至你选择的服务商，服务商的费用和数据政策可能适用。'],
      ['撤销与恢复', '符合条件的最近一次整理可尝试撤销，但受权限和文件可用性限制。撤销无法恢复被覆盖文件原有的内容。'],
    ],
    privacyLink: '了解数据处理方式', supportLink: '获取使用支持',
    pricingLabel: '开始使用', pricingTitle: '先从几个文件开始。',
    pricingText: '免费版提供累计 50 次文件操作额度，并非每月重置。可选的 Pro 购买可解除这一额度限制。当前当地价格以 App Store 及应用内购买确认页为准。',
    pricingAI: '第三方 AI 服务独立提供，可能按使用量收费。',
    faqTitle: '你可能还想了解。',
    faqs: [
      ['一定要配置 AI 吗？', '不用。可以直接手动选择目标位置并审核计划，无需配置 AI。云端 AI 需要网络；Ollama 需要另行运行的服务和模型。'],
      ['会替换我现有的目录结构吗？', '你可以沿用已有目录，也可以初始化 Johnny.Decimal 模板。在首次设置中，由你选择归档目录和来源文件夹。'],
      ['所有操作都可以撤销吗？', '不是。恢复取决于操作类型、文件可用性、权限和保留的恢复数据。部分恢复可能保留归档副本，或需要手动处理。撤销不能恢复被覆盖的旧内容，请保留独立备份。'],
      ['在哪里寻求帮助？', '支持页提供手动整理流程、连接检查和恢复提示。你也可以发邮件至 fileflow@theunclej.com。'],
    ],
    docs: {
      guide: { title: '从三个文件开始。', description: '做一次小尝试，走完第一次整理。', sections: [
        ['1. 准备一个小实验', '在 Mac 本地创建两个互不包含的目录，例如“FileFlow 试用来源”和“FileFlow 试用归档”。把三份不含隐私的文件副本放入来源目录，例如一份 TXT、一张 PNG 和一份 PDF。原始文件留在别处，不用唯一副本试验。这次先不使用云同步目录或外接磁盘。'],
        ['2. 选择来源与归档位置', '首次设置时，选择并授权试用归档目录。使用 Johnny.Decimal 模板，或沿用已有结构并提前创建一个目标子目录。再添加试用来源文件夹。初始化前核对完整路径：设置可能创建 FileFlow 管理数据，这与整理来源文件是两件事。第一次先跳过 AI。'],
        ['3. 为文件选择归属', '打开 Inbox 并扫描来源目录，选中三个示例文件，点击 Archive to...，选择目标位置并确认。接下来会打开 Review Plan，此时尚未执行整理计划。'],
        ['4. 把计划看清楚', '核对选中的文件、完整来源与目标路径，以及重名文件的处理方式。第一次试用不要覆盖已有文件。需要调整时选择 Back 返回；确认正确后，再选择 Execute 执行。即使本次整理能够撤销，也不能找回被覆盖文件的旧内容。'],
        ['5. 检查实际结果', '先阅读操作结果，再打开目标目录，确认文件能够正常打开。部分失败不能算作整批成功。目录浏览和统计可以帮助核对，但索引或操作收据本身不能证明每个文件都完整可用。'],
        ['6. 尝试一次符合条件的撤销', '使用最近一次整理可用的撤销入口，并阅读提示。普通归档操作的恢复可能找回来源文件，同时保留归档副本；也可能使用 Recovered 位置或需要手动处理。完成后检查两边的实际文件。如果撤销不可用，先保留文件和元数据，查看具体原因。'],
        ['7. 需要时，再加入 AI', '在设置中配置端点、模型、协议和你有权使用的密钥，验证连接后保存。连接测试成功不代表分类一定正确。发起分类后，逐个审核建议的目标位置，再通过 Preview Selection 查看计划。云端请求会向服务商发送元数据和候选位置，请继续使用不含敏感信息的示例文件。'],
        ['如果过程被中断', '重试前先核对来源和目标文件，目标处可能存在不完整副本。中止或忽略不等于撤销，也不会自动清理残片或恢复文件。不要反复执行被阻止的计划，也不要删除管理数据来绕过提示。保留原始文件和应用报告的恢复信息。'],
        ['如果根目录或管理数据丢失', '先确认原目录或磁盘仍然可用，必要时重新授权。不要把暂时不可访问的目录当成空目录重新初始化。恢复收据可能帮助说明最近操作，但不能重建丢失的文件内容。请找回原位置或使用独立备份。'],
        ['然后，再多整理一点', '看过计划、核对过结果，并理解恢复的实际效果后，再逐步增加文件。不必第一次就整理整个磁盘。'],
      ] },
      support: { title: '支持', description: '先从少量文件开始，把每一步看清楚。', sections: [
        ['先建一个测试文件夹', '首次使用时，建议用可丢弃的示例文件。选择专用归档目录，沿用包含目标文件夹的已有结构，或初始化 Johnny.Decimal 模板。再添加独立的来源文件夹。AI 设置可以跳过。'],
        ['1.1 的手动整理流程', '打开 Inbox 并扫描，选择文件，点击 Archive to... 并选择目标位置。在 Review Plan 中核对来源路径与重名处理方式。选择 Execute 执行整理，或 Back 返回而不执行计划。完成后检查操作结果。'],
        ['审核分类建议', '对于已经出现在 Review 中的条目，可以调整目标位置，再通过 Preview Selection 检查计划。仅扫描文件，不代表一定会在 Review 中生成已分类条目。'],
        ['连接 AI 服务', '在设置中填写服务商端点、模型及匹配的协议：OpenAI 兼容或 Anthropic Messages。输入你有权使用的 API 密钥，验证连接后保存。Ollama 需要另行运行服务并准备模型。连接测试会发送合成文件名；实际分类会发送文件元数据和候选目标位置。'],
        ['文件夹权限与缺失文件', '检查来源和归档目录是否可访问。如 macOS 授权失效，请在设置中重新授权。使用 iCloud Drive 时，确认文件已下载。整理过程中避免移动或重命名正在使用的来源与归档目录。'],
        ['操作中断与撤销', '重试之前，先阅读操作结果和恢复信息。不要通过删除恢复元数据来消除警告。符合条件的撤销可能恢复文件、保留归档副本、使用 Recovered 位置，或需要手动处理。它无法重建已删除的内容，也无法恢复覆盖前的旧内容。'],
        ['恢复购买', '使用购买时的 Apple 账户登录，并在设置中使用恢复购买功能。此操作需要与 App Store 通信。如果权益未恢复，请记录页面显示的结果并联系支持。'],
        ['联系我们', '请发邮件至 fileflow@theunclej.com，附上应用版本、macOS 版本、复现步骤和错误信息。截图中的私人路径和文件名请先打码，不要发送 API 密钥或敏感文档。'],
      ] },
      philosophy: { title: '产品理念', description: '整理应当保留上下文，而不是抹去它。', sections: [
        ['不是每个文件夹都需要重来', '收件箱和项目归档承担不同职责。下载目录里的文件可能需要分类；一个项目文件夹却可能已经拥有有意义的内部秩序。已有结构应该在整理流程中得到尊重。'],
        ['先决定，再自动化', '建议不等于授权。FileFlow 将选择归属位置与执行整理计划分开，让你在变化发生前，先检查将发生什么。'],
        ['AI 是助手，不是前提', '手动整理本身就是一条完整路径。外部模型可以提供分类建议，但是否使用它，应当始终由你决定。'],
        ['记录有用，备份不同', '活动记录和恢复记录帮助你理解一次操作，但不是文件所有历史状态的副本。诚实地说明限制，比承诺一切都能撤销更重要。'],
        ['让秩序适应工作', '可以使用 Johnny.Decimal 模板，也可以沿用自己的目录。目标不是完美的分类法，而是一套能持续使用、再次打开时仍能理解的结构。'],
      ] },
      privacy: { title: '隐私', description: '本地整理，明确的外部连接。', updated: '更新于 2026 年 9 月 12 日', sections: [
        ['适用范围', '本页说明 FileFlow 1.1 及本产品网站的数据处理方式。核心手动整理无需 FileFlow 账号。可选 AI 连接、App Store 服务、云同步目录和支持邮件各有不同的数据流。'],
        ['文件与本地存储', '核心文件整理在你的 Mac 上运行，并使用你授权的文件夹。归档目录中可能包含 .fileflow 索引、配置、操作历史、日志和恢复元数据。应用也会在自身的应用支持目录保存配置、文件夹访问书签和恢复摘要。API 凭据保存在 macOS 钥匙串中。这些记录可能含有文件名和路径。'],
        ['可选 AI 请求', '当你请求云端分类时，FileFlow 会向配置的端点发送文件元数据和候选目标位置，可能包括文件名、扩展名、来源文件夹名称、文件大小与目录结构。分类提示使用元数据，而非文件内容；但名称和路径本身仍可能泄露敏感信息。连接验证会向该端点发送合成文件名。'],
        ['你选择的服务商', '配置的 AI 服务商接收请求，并按其自身的数据政策处理。其保留方式、可用性和费用不由 FileFlow 控制。Ollama 连接需要独立的服务和模型；端点是否位于本机，取决于你的配置。'],
        ['Apple 与云同步目录', 'App Store 购买和恢复通过 Apple 处理。如果你整理的是 iCloud Drive 或其他同步位置中的文件，该服务可能按自身政策同步变更。FileFlow 不会将云同步目录变成仅离线的目录。'],
        ['诊断与支持', 'FileFlow 在本地保留操作诊断信息；1.1 构建未启用其可选的第三方崩溃上报集成。如果你向支持邮箱发信，我们会使用你的邮箱地址及你主动提供的信息来回应请求。请勿发送 API 密钥或敏感文件内容。'],
        ['本网站', '本网站未嵌入广告追踪器或分析脚本。托管服务商可能为提供网站而处理常规连接信息。点击 App Store 链接后，你将访问 Apple 的服务。'],
        ['你的选择', '你可以完全不使用 AI，并通过应用移除已保存的 AI 凭据。卸载应用不一定会清除本地配置和恢复记录。删除元数据或撤销目录权限前，请先完成待处理的恢复操作，并保留文件备份。隐私问题请联系 fileflow@theunclej.com。'],
      ] },
      terms: { title: '使用条款', description: '明确使用文件整理工具时的责任。', updated: '更新于 2026 年 9 月 12 日', sections: [
        ['使用 FileFlow', '使用 FileFlow 即表示你同意这些条款。FileFlow 是一款 Mac 文件整理工具，提供手动工作流程与可选的 AI 分类。你需要在执行前审核目标位置并批准整理计划。'],
        ['你的责任', '你负责维护独立备份、授权适当的文件夹，并审核拟执行的文件操作。撤销受文件可用性、权限和恢复数据限制，不能恢复被覆盖文件原有的内容。FileFlow 不是备份服务。'],
        ['可选 AI 服务', '你管理自己的服务商凭据，并承担服务商收取的费用。云端 AI 按服务商政策接收元数据和候选目标位置。Ollama 需要独立的服务和模型。服务兼容性与可用性取决于选定的端点、模型和协议。'],
        ['购买', 'FileFlow 提供有限免费额度和可选的 Pro 购买。适用价格和购买条款以 App Store 及应用内购买确认页为准。第三方 AI 费用单独计算。退款申请由 Apple 按其 App Store 政策处理。'],
        ['免责声明', 'FileFlow 按现状提供，不作任何形式的保证。尽管应用包含计划审核、校验、操作记录和恢复机制，这些措施不能保证不会发生数据丢失。在适用法律允许的范围内，我们不对数据丢失承担责任。'],
        ['变更与联系', '我们可能更新这些条款。条款变更后继续使用 FileFlow，表示你接受更新后的条款。如有疑问，请联系 fileflow@theunclej.com。'],
      ] },
    },
  },
};
