import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { site, copy } from '../content/site.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const pages = ['index', 'philosophy', 'support', 'privacy', 'terms', 'guide', 'johnny-decimal'];
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const lines = value => esc(value).replaceAll('\n', ' <br>');
const href = (locale, page) => `${locale === 'zh' ? 'zh/' : ''}${page}.html`;

function layout(locale, page, body) {
  const c = copy[locale];
  const prefix = locale === 'zh' ? '../' : '';
  const isHome = page === 'index';
  const title = isHome ? c.title : `${c.docs[page].title} | FileFlow`;
  const description = isHome ? c.description : c.docs[page].description;
  const canonical = `${site.origin}/${href(locale, page)}`;
  const other = locale === 'zh' ? 'en' : 'zh';
  const current = name => page === name ? ' aria-current="page"' : '';
  const nav = `<a href="index.html#workflow">${c.nav[0]}</a><a href="guide.html"${current('guide')}>${c.nav[1]}</a><a href="support.html"${current('support')}>${c.nav[2]}</a>`;
  return `<!doctype html>
<!-- Generated by scripts/build.mjs. Edit content/site.mjs or the template, then rebuild. -->
<html lang="${c.lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${canonical}">
  <link rel="alternate" hreflang="en" href="${site.origin}/${href('en', page)}">
  <link rel="alternate" hreflang="zh-Hans" href="${site.origin}/${href('zh', page)}">
  <link rel="alternate" hreflang="x-default" href="${site.origin}/${href('en', page)}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${site.origin}/images/v1.1/01-review-workflow.png">
  <meta property="og:locale" content="${locale === 'zh' ? 'zh_CN' : 'en_US'}">
  <link rel="icon" type="image/png" href="${prefix}images/v1.1/app-icon.png">
  <link rel="stylesheet" href="${prefix}site.css">
  <script src="${prefix}site.js" defer></script>
</head>
<body class="${isHome ? 'home' : 'document'}">
  <a class="skip-link" href="#main">${c.skip}</a>
  <header class="site-header"><div class="nav-inner">
    <a class="brand" href="index.html" aria-label="FileFlow${locale === 'zh' ? ' 首页' : ' home'}"><img src="${prefix}images/v1.1/app-icon.png" width="32" height="32" alt="">FileFlow</a>
    <nav aria-label="${locale === 'zh' ? '主导航' : 'Main navigation'}">${nav}</nav>
    <a class="language" href="${prefix}${href(other, page)}" lang="${copy[other].lang}" hreflang="${copy[other].lang}">${c.other}</a>
  </div></header>
  <main id="main">${body}</main>
  <footer class="site-footer"><div class="footer-inner">
    <div class="footer-brand"><img src="${prefix}images/v1.1/app-icon.png" width="28" height="28" alt=""><span>FileFlow</span></div>
    <nav aria-label="${locale === 'zh' ? '页脚导航' : 'Footer navigation'}">${pages.map((name, i) => `<a href="${name}.html"${current(name)}>${c.footer[i]}</a>`).join('')}</nav>
    <p>© 2025 Uncle J. All rights reserved.</p>
  </div></footer>
  <dialog class="image-dialog" aria-label="${c.expand}"><button class="dialog-close" type="button" aria-label="${c.close}" title="${c.close}"><span aria-hidden="true">×</span></button><img width="2720" height="1440" alt=""></dialog>
</body>
</html>
`;
}

function home(locale) {
  const c = copy[locale];
  const p = locale === 'zh' ? '../' : '';
  const imagePath = file => `${p}images/v1.1/${file}`;
  const shot = (file, alt, eager = false) => `<a class="screenshot-link" href="${imagePath(file)}" data-zoom aria-label="${c.expand}: ${esc(alt)}"><img src="${imagePath(file)}" alt="${esc(alt)}" width="2720" height="1440" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'}></a>`;
  const cta = `<a class="button" href="${site.store}">${c.download}<span aria-hidden="true">↗</span></a>`;
  return `
    <section class="hero" aria-labelledby="product-name">
      <div class="hero-copy">
        <p class="eyebrow">${c.eyebrow}</p>
        <h1 id="product-name">FileFlow</h1>
        <p class="hero-lead">${lines(c.lead)}</p>
        <p class="hero-intro">${lines(c.intro)}</p>
        ${cta}
        <p class="requirement">${c.requirement}</p>
      </div>
      <div class="hero-media">${shot('01-review-workflow.png', c.reviewAlt, true)}</div>
    </section>
    <section class="workflow section" id="workflow" aria-labelledby="workflow-title">
      <div class="section-intro"><p class="eyebrow">${c.workflowLabel}</p><h2 id="workflow-title">${c.workflowTitle}</h2><p>${c.workflowIntro}</p></div>
      <div class="workspace-gallery">
        <div class="gallery-tabs" aria-label="${c.nav[0]}">${c.screens.map((s, i) => `<button type="button" id="tab-${s.key}" data-tab="${s.key}"><span class="tab-number">0${i + 1}</span>${s.label}</button>`).join('')}</div>
        ${c.screens.map(s => `<section class="gallery-panel" id="panel-${s.key}" data-panel="${s.key}"><div class="panel-copy"><h3>${s.title}</h3><div><p>${s.text}</p>${s.key === 'browse' ? `<a class="text-link method-link" href="johnny-decimal.html">${c.methodLink}<span aria-hidden="true"> →</span></a>` : ''}</div></div>${shot(s.file, s.alt)}</section>`).join('')}
        <p class="caption">${c.screenshotNote}</p>
      </div>
    </section>
    <section class="principles section" aria-labelledby="principles-title"><div class="content-width">
      <div class="section-intro"><p class="eyebrow">${c.principlesLabel}</p><h2 id="principles-title">${c.principlesTitle}</h2></div>
      <div class="principle-grid">${c.principles.map(([n, title, text]) => `<div class="principle"><span class="number">${n}</span><h3>${title}</h3><p>${text}</p></div>`).join('')}</div>
      <a class="text-link" href="philosophy.html">${c.principlesLink}<span aria-hidden="true"> →</span></a>
    </div></section>
    <section class="boundaries section" aria-labelledby="limits-title"><div class="content-width">
      <div class="section-intro"><p class="eyebrow">${c.limitsLabel}</p><h2 id="limits-title">${c.limitsTitle}</h2></div>
      <div class="boundary-grid">${c.limits.map(([title, text], i) => `<div><h3>${title}</h3><p>${text}</p><a class="text-link" href="${i ? 'support' : 'privacy'}.html">${i ? c.supportLink : c.privacyLink}<span aria-hidden="true"> →</span></a></div>`).join('')}</div>
    </div></section>
    <section class="section faq"><div class="reading-width"><h2>${c.faqTitle}</h2>${c.faqs.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<div class="guide-invitation"><p>${c.guideIntro}</p><a class="text-link" href="guide.html">${c.guideLink}<span aria-hidden="true"> →</span></a></div></div></section>
    <section class="download-section section"><div class="reading-width"><img class="download-icon" src="${imagePath('app-icon.png')}" width="80" height="80" alt=""><p class="eyebrow">${c.pricingLabel}</p><h2>${c.pricingTitle}</h2><p>${c.pricingText}</p>${cta}<p class="small">${c.pricingAI}</p></div></section>
  `;
}

function document(locale, page) {
  const c = copy[locale], d = c.docs[page];
  const prefix = locale === 'zh' ? '../' : '';
  const guide = page === 'guide';
  const figures = { 3: ['02-plan-commit.png', c.screens[0].alt], 4: ['03-browse-structure.png', c.screens[1].alt], 6: ['01-review-workflow.png', c.reviewAlt] };
  const figure = index => {
    if (!guide || !figures[index]) return '';
    const [file, alt] = figures[index];
    return `<figure class="guide-figure"><a href="${prefix}images/v1.1/${file}" data-zoom aria-label="${c.expand}: ${esc(alt)}"><img src="${prefix}images/v1.1/${file}" width="2720" height="1440" loading="lazy" alt="${esc(alt)}"></a><figcaption>${c.screenshotNote}</figcaption></figure>`;
  };
  return `<article class="document-body reading-width"><header class="document-header"><p class="eyebrow">FILEFLOW</p><h1>${d.title}</h1><p class="document-lead">${d.description}</p>${d.updated ? `<p class="updated">${d.updated}</p>` : ''}</header>
    ${guide ? `<nav class="guide-toc" aria-label="${locale === 'zh' ? '本页目录' : 'On this page'}">${d.sections.map(([title], i) => `<a href="#step-${i + 1}">${title}</a>`).join('')}</nav>` : ''}
    ${page === 'support' ? `<div class="support-guide"><p>${c.guideIntro}</p><a class="text-link" href="guide.html">${c.guideLink}<span aria-hidden="true"> →</span></a></div>` : ''}
    ${d.sections.map(([title, text], i) => `<section id="step-${i + 1}"><h2>${title}</h2><p>${esc(text).replaceAll(site.email, `<a href="mailto:${site.email}">${site.email}</a>`)}</p>${guide && i === 1 ? `<a class="text-link" href="johnny-decimal.html">${c.methodLink}<span aria-hidden="true"> →</span></a>` : ''}${figure(i)}</section>`).join('')}
    <a class="text-link" href="index.html">${locale === 'zh' ? '返回 FileFlow' : 'Back to FileFlow'}<span aria-hidden="true"> →</span></a></article>`;
}

function method(locale) {
  const c = copy[locale], d = c.docs['johnny-decimal'];
  const prefix = locale === 'zh' ? '../' : '';
  const figure = (file, alt, caption) => `<figure class="guide-figure"><a href="${prefix}images/v1.1/${file}" data-zoom aria-label="${c.expand}: ${esc(alt)}"><img src="${prefix}images/v1.1/${file}" width="2720" height="1440" loading="lazy" alt="${esc(alt)}"></a><figcaption>${esc(caption)}</figcaption></figure>`;
  const extra = [
    `<figure class="method-example"><figcaption>${esc(d.exampleLabel)}</figcaption><pre><code>${esc(d.example)}</code></pre></figure><dl class="method-key">${d.parts.map(([id, label, text]) => `<div><dt><code>${id}</code> ${esc(label)}</dt><dd>${esc(text)}</dd></div>`).join('')}</dl><p>${esc(d.exampleNote)}</p><a class="text-link" href="https://johnnydecimal.com/documentation/introduction">${esc(d.officialIntro)}<span aria-hidden="true"> ↗</span></a>`,
    `${figure('03-browse-structure.png', c.screens[1].alt, d.browseCaption)}<p>${esc(d.indexNote)}</p>`,
    `<ol class="method-steps">${d.steps.map(([title, text]) => `<li><h3>${esc(title)}</h3><p>${esc(text)}</p></li>`).join('')}</ol>${figure('02-plan-commit.png', c.screens[0].alt, d.planCaption)}`,
    '',
    `<ul class="method-resources"><li><a href="https://johnnydecimal.com/documentation">${esc(d.resources[0])}</a></li><li><a href="https://johnnydecimal.com/support/about-legal/licence">${esc(d.resources[1])}</a></li></ul><div class="method-actions"><a class="button" href="${site.store}">${c.download}<span aria-hidden="true">↗</span></a><a class="text-link" href="guide.html">${c.guideLink}<span aria-hidden="true"> →</span></a></div>`,
  ];
  const officialTools = `<section id="official-tools"><h2>${esc(d.tools.title)}</h2><p>${esc(d.tools.terminal)}</p><ul class="method-resources"><li><a href="https://johnnydecimal.com/jdhq/jd-cli">${esc(d.tools.guideLink)}</a></li><li><a href="https://johnnydecimal.com/blog/0245-jd-cli-now-creates-folders">${esc(d.tools.updateLink)}</a></li></ul><p>${esc(d.tools.visual)}</p></section>`;
  return `<article class="document-body reading-width method-body"><header class="document-header"><p class="eyebrow">${d.label}</p><h1>${lines(d.heading || d.title)}</h1><p class="document-lead">${d.lead}</p></header>
    ${d.sections.map(([title, text], i) => `<section id="method-${i + 1}"><h2>${esc(title)}</h2><p>${esc(text)}</p>${extra[i]}</section>${i === 3 ? officialTools : ''}`).join('')}
    <p class="method-attribution">${esc(d.attribution)}</p>
    <a class="text-link" href="index.html">${locale === 'zh' ? '返回 FileFlow' : 'Back to FileFlow'}<span aria-hidden="true"> →</span></a></article>`;
}

await mkdir(`${root}zh`, { recursive: true });
for (const locale of Object.keys(copy)) {
  for (const page of pages) {
    const html = layout(locale, page, page === 'index' ? home(locale) : page === 'johnny-decimal' ? method(locale) : document(locale, page));
    await writeFile(`${root}${href(locale, page)}`, html.replace(/[\t ]+$/gm, ''));
  }
}
const urls = Object.keys(copy).flatMap(locale => pages.map(page => `${site.origin}/${href(locale, page)}`));
await writeFile(`${root}sitemap.xml`, `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url => `  <url><loc>${url}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Built ${urls.length} bilingual static pages.`);
